site_name: Sea Saba Knowledge Base

theme: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Business App:
      - Quick Start Guide: BusinessApp/QuickStart.md
      - Contract Management: BusinessApp/ContractManagement.md
      - Dive Package Configuration: BusinessApp/DivePackages.md
      - Hotel & Room Management: BusinessApp/HotelManagement.md
      - Dive Logging & Operations: BusinessApp/DiveLogging.md
      - Equipment Maintenance: BusinessApp/Maintenance.md
      - Asset Tracking: BusinessApp/AssetManagement.md
      - Analytics & Reporting: BusinessApp/Analytics.md
      - Troubleshooting Common Issues: BusinessApp/Troubleshooting.md
  - General Information:
      - Problem-Solving & Issue Escalation: GeneralInformation/ProblemSolving.md
      - Diving & Snorkeling Info: GeneralInformation/DivingSnorkelingInfo.md
      - Random Important Information: GeneralInformation/RandomImportantInfo.md
  - Freight:
      - Hassell Free Freight Shipping Procedures: Freight/ShippingHassellFree.md
      - Managing Freight Data and Communication with Hassell Free: Freight/HassellFreeDocs.md
  - Retail Operations:
      - Checkfront: RetailOperations/Checkfront.md
      - Diving Flowchart: RetailOperations/DivingFlowchart.md
      - Non-Diving Flowchart: RetailOperations/NonDivingFlowchart.md
      - Shopify POS: RetailOperations/ShopifyPOS.md
      - Store Opening & Closing Instructions: RetailOperations/RetailOpenClosing.md
  - Diving Operations:
      - Morning Routine: DiveOperations/MorningRoutine.md
      - Boat Briefing Overview: DiveOperations/BoatBriefingOverview.md
      - Dive Briefing Overview: DiveOperations/DiveBriefingOverview.md
      - Diver Support Level Policy: DiveOperations/DiverSupportLevelPolicy.md
      - Packing Lists: DiveOperations/PackingLists.md
      - Surface Support: DiveOperations/SurfaceSupport.md
      - Rinsing & Putting Away Equipment: DiveOperations/RinsingGear.md
      - Logging Dives: DiveOperations/DiveLogApp.md
      - Marine Park Rules: DiveOperations/MarineParkRules.md
  - Equipment:
      - Vehicle Maintenance SOP: Equipment/SOPVehicleMaint.md
      - Compressor Operation: Equipment/CompressorOperation.md
      - Compressor Servicing: Equipment/CompressorServicing.md
      - Using Sailclear for Vessel Clearance: Equipment/ClearanceOfVessels.md
      - ECU Replacement on OXE Engines: Equipment/ECU.md
  - Checkfront:
      - Checkfront Overview: Checkfront/CheckfrontOverview.md

plugins:
  - search
  - mermaid2

